#!/bin/sh

empty_file(){
	cat < /dev/null > "$1"
}

clrtoeol(){
	printf '[2K'
}

msleep(){
	sleep `(echo scale=5; echo $1 / 1000) | bc`
}

if [ $# -eq 0 ]
then
	echo "Usage: $0 args-for-sdb..." >&2
	exit 1
fi

our="$(readlink -f "$0" | xargs dirname)"
dir="$("$our/sdb" $@)"

cd "$dir" || exit $?

empty_file log
while :
do
	while ! [ -e ready ]
	do
		printf 'waiting for sdb...\r'
		sleep 1
		clrtoeol
	done
	rm ready

	cat last | tee -a log
	empty_file last

	echo -n "(sdb) "
	read line || break
	echo "$line" > cmd
	msleep 100
done

kill "`cat pid`"
