const.o: const.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h const.h cc1.h ../util/std.h
decl.o: decl.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/alloc.h ../util/platform.h ../util/dynarray.h \
 ../util/dyn.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h macros.h sue.h const.h cc1.h ../util/std.h fold.h funcargs.h
expr.o: expr.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/alloc.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h cc1.h ../util/std.h const.h
fold.o: fold.c defs.h ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h cc1.h ../util/std.h fold.h fold_sym.h ../util/platform.h \
 const.h ../util/alloc.h ../util/dynarray.h ../util/dyn.h \
 ../util/dynmap.h sue.h decl_init.h pack.h funcargs.h out/lbl.h \
 stmt_ctx.h
fold_sue.o: fold_sue.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/where.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h cc1.h ../util/std.h fold.h sue.h const.h pack.h \
 defs.h fold_sue.h
fold_sym.o: fold_sym.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h cc1.h ../util/std.h fold_sym.h ../util/platform.h \
 ../util/dynarray.h ../util/dyn.h pack.h sue.h fold.h fold_sue.h \
 decl_init.h out/lbl.h const.h
funcargs.o: funcargs.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/alloc.h ../util/dynarray.h ../util/dyn.h \
 data_structs.h tree.h type.h expr.h basic_blk/tdefs.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_assign_compound.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h \
 ops/expr_deref.h ops/expr_struct.h ops/expr_compound_lit.h \
 ops/expr_string.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h type_ref.h funcargs.h \
 cc1.h ../util/std.h fold.h
gen_c.o: gen_c.c
gen_str.o: gen_str.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/platform.h ../util/dynarray.h ../util/dyn.h \
 data_structs.h tree.h type.h expr.h basic_blk/tdefs.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_assign_compound.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h \
 ops/expr_deref.h ops/expr_struct.h ops/expr_compound_lit.h \
 ops/expr_string.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h type_ref.h macros.h \
 cc1.h ../util/std.h sue.h gen_str.h str.h const.h decl_init.h funcargs.h \
 out/asm.h
gen_style.o: gen_style.c ../util/util.h ../util/where.h \
 ../util/compiler.h ../util/assert.h ../util/dynarray.h ../util/dyn.h \
 data_structs.h tree.h type.h expr.h basic_blk/tdefs.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_assign_compound.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h \
 ops/expr_deref.h ops/expr_struct.h ops/expr_compound_lit.h \
 ops/expr_string.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h type_ref.h cc1.h \
 ../util/std.h gen_style.h gen_asm.h decl_init.h out/asm.h
pack.o: pack.c pack.h ../util/platform.h
parse_attr.o: parse_attr.c
parse_init.o: parse_init.c
parse_type.o: parse_type.c ../util/util.h ../util/where.h \
 ../util/compiler.h ../util/assert.h ../util/alloc.h ../util/dynarray.h \
 ../util/dyn.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h decl_init.h funcargs.h tokenise.h tokconv.h sue.h cc1.h \
 ../util/std.h parse.h parse_type.h parse_attr.c parse_init.c
pass1.o: pass1.c ../util/where.h ../util/compiler.h ../util/dynarray.h \
 ../util/dyn.h ../util/util.h ../util/where.h ../util/assert.h \
 data_structs.h tree.h type.h expr.h basic_blk/tdefs.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_assign_compound.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h \
 ops/expr_deref.h ops/expr_struct.h ops/expr_compound_lit.h \
 ops/expr_string.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h type_ref.h fold_sym.h \
 tokenise.h tokconv.h parse.h parse_type.h cc1.h ../util/std.h fold.h \
 const.h pass1.h
stmt.o: stmt.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/alloc.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h cc1.h ../util/std.h
str.o: str.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h ../util/alloc.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h str.h macros.h
sue.o: sue.c ../util/alloc.h ../util/util.h ../util/where.h \
 ../util/compiler.h ../util/assert.h ../util/dynarray.h ../util/dyn.h \
 data_structs.h tree.h type.h expr.h basic_blk/tdefs.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_assign_compound.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h \
 ops/expr_deref.h ops/expr_struct.h ops/expr_compound_lit.h \
 ops/expr_string.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h type_ref.h sue.h cc1.h \
 ../util/std.h
sym.o: sym.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h ../util/alloc.h macros.h ../util/dynarray.h ../util/dyn.h \
 sue.h funcargs.h
tokconv.o: tokconv.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h tokenise.h tokconv.h macros.h cc1.h ../util/std.h
tokenise.o: tokenise.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/assert.h data_structs.h tree.h type.h expr.h basic_blk/tdefs.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_assign_compound.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h ops/expr_struct.h \
 ops/expr_compound_lit.h ops/expr_string.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 type_ref.h tokenise.h ../util/alloc.h ../util/str.h str.h cc1.h \
 ../util/std.h
tree.o: tree.c ../util/alloc.h ../util/util.h ../util/where.h \
 ../util/compiler.h ../util/assert.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h macros.h ../util/platform.h sue.h cc1.h \
 ../util/std.h defs.h
type.o: type.c ../util/where.h ../util/compiler.h ../util/util.h \
 ../util/where.h ../util/assert.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h sue.h
type_ref.o: type_ref.c ../util/where.h ../util/compiler.h ../util/util.h \
 ../util/where.h ../util/assert.h data_structs.h tree.h type.h expr.h \
 basic_blk/tdefs.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_assign_compound.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h ops/expr_deref.h \
 ops/expr_struct.h ops/expr_compound_lit.h ops/expr_string.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h type_ref.h sue.h const.h funcargs.h cc1.h ../util/std.h \
 type_ref_is.h
type_ref_is.o: type_ref_is.c ../util/where.h ../util/compiler.h \
 ../util/util.h ../util/where.h ../util/assert.h ../util/platform.h \
 data_structs.h tree.h type.h expr.h basic_blk/tdefs.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_assign_compound.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h \
 ops/expr_deref.h ops/expr_struct.h ops/expr_compound_lit.h \
 ops/expr_string.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h type_ref.h sue.h \
 const.h type_ref_is.h
